# * Set name of your application
application: Awesome App

# * Username/password for HTTP Auth
username: jim
password: xxx

# * Full path to your Rails application
path: /var/www/awesome_app

# * Capistrano command (defaults to "deploy" if not set)
cap_command: deploy:migration

# * Setup notifications (look in notifiers directory)
notifiers:
  - twitter_notifier:
      login: jim
      password: xxx
      success_template: 'Awesome App has been updated! {{ repository.revision }}: {{ repository.message }}'
  - xmpp_notifier:
      login: jim@mail.com
      password: xxx
      recipients:
        - bill@mail.com
        - sarah@mail.com
      success_template: 'A new revision ({{ repository.revision }}) has been pushed: {{ repository.message }}'
      failure_template: 'Deployment of ({{ repository.revision }}) failed.'
  - irc_notifier:
      uri: 'irc://irc.freenode.net:6667/test'
      success_template: 'A new revision ({{ repository.revision }}) has been pushed: {{ repository.message }}'